Repository futureleadersupc/waw-backend-cs, pull requests merged in 2022-06, with the labels that each got.

#1 ci: add base branch check for PRs
  .github/workflows/branches.yml
Labels: ci

#2 chore: rename launch profiles for Rider
  .run/WAW.API_ IIS Express.run.xml
  .run/WAW.API_ Standalone.run.xml
  WAW.API/Properties/launchSettings.json
Labels: chore

#4 docs(swagger): Enabled Annotations
  WAW.API/Program.cs
  WAW.API/WAW.API.csproj
Labels: documentation

#6 ci: various fixes
  .github/workflows/branches.yml
  .github/workflows/dotnet.yml
  .github/workflows/reports.yml
Labels: ci

#7 chore(ide): VS Code settings
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
Labels: chore

#8 fix(companies): Endpoint changes
  WAW.API/Company/Controllers/CompaniesController.cs
  WAW.API/Company/Resources/CompanyRequest.cs
  WAW.API/Company/Resources/CompanyResource.cs
Labels: documentation, chore

#9 docs: WAW API documentation
  WAW.API/Program.cs
Labels: documentation, chore

#10 feat(jobs): Job offers endpoint
  WAW.API/Job/Controllers/OffersController.cs
  WAW.API/Job/Domain/Models/Offer.cs
  WAW.API/Job/Domain/Repositories/IOfferRepository.cs
  WAW.API/Job/Domain/Services/Communication/OfferResponse.cs
  WAW.API/Job/Domain/Services/IOfferService.cs
  WAW.API/Job/Mapping/ModelToResourceProfile.cs
  WAW.API/Job/Mapping/ResourceToModelProfile.cs
  WAW.API/Job/Persistence/Repositories/OfferRepository.cs
  WAW.API/Job/Resources/OfferRequest.cs
  WAW.API/Job/Resources/OfferResource.cs
  WAW.API/Job/Services/OfferService.cs
  WAW.API/Migrations/20220610184650_CreateJobs.Designer.cs
  WAW.API/Migrations/20220610184650_CreateJobs.cs
  WAW.API/Program.cs
  WAW.API/WAW.API.csproj
  WAW.API/Weather/Persistence/Contexts/AppDbContext.cs
Labels: enhancement

#12 refactor: shared files
  WAW.API.Tests/Drivers/Driver.cs
  WAW.API.Tests/Features/Forecast.feature
  WAW.API.Tests/Hooks/ForecastHooks.cs
  WAW.API.Tests/Steps/ForecastStepDefinitions.cs
  WAW.API.Tests/WAW.API.Tests.csproj
  WAW.API/Auth/Injection/AuthInjections.cs
  WAW.API/Auth/Mapping/AuthModelToResourceProfile.cs
  WAW.API/Auth/Mapping/AuthResourceToModelProfile.cs
  WAW.API/Auth/Mapping/ModelToResourceProfile.cs
  WAW.API/Auth/Mapping/ResourceToModelProfile.cs
  WAW.API/Auth/Persistence/Repositories/UserRepository.cs
  WAW.API/Auth/Services/UserService.cs
  WAW.API/Company/Injection/CompanyInjections.cs
  WAW.API/Company/Mapping/CompanyModelToResourceProfile.cs
  WAW.API/Company/Mapping/CompanyResourceToModelProfile.cs
  WAW.API/Company/Mapping/ModelToResourceProfile.cs
  WAW.API/Company/Mapping/ResourceToModelProfile.cs
  WAW.API/Company/Persistence/Repositories/CompanyRepository.cs
  WAW.API/Company/Services/CompanyService.cs
  WAW.API/Job/Injection/JobInjections.cs
  WAW.API/Job/Mapping/JobModelToResourceProfile.cs
  WAW.API/Job/Mapping/JobResourceToModelProfile.cs
  WAW.API/Job/Mapping/ModelToResourceProfile.cs
  WAW.API/Job/Mapping/ResourceToModelProfile.cs
  WAW.API/Job/Persistence/Repositories/OfferRepository.cs
  WAW.API/Job/Services/OfferService.cs
  WAW.API/Migrations/20220604101157_InitialCreate.Designer.cs
  WAW.API/Migrations/20220609230932_CreateCompanies.Designer.cs
  WAW.API/Migrations/20220610184650_CreateJobs.Designer.cs
  WAW.API/Migrations/20220611023856_User.Designer.cs
  WAW.API/Migrations/20220611102417_UpdatedJobsProperties.Designer.cs
  WAW.API/Migrations/AppDbContextModelSnapshot.cs
  WAW.API/Program.cs
  WAW.API/Shared/Domain/Repositories/IUnitOfWork.cs
  WAW.API/Shared/Injection/AppInjections.cs
  WAW.API/Shared/Mapping/ModelToResourceProfile.cs
  WAW.API/Shared/Mapping/ResourceToModelProfile.cs
  WAW.API/Shared/Persistence/Contexts/AppDbContext.cs
  WAW.API/Shared/Persistence/Repositories/BaseRepository.cs
  WAW.API/Shared/Persistence/Repositories/UnitOfWork.cs
  WAW.API/WAW.API.csproj
  WAW.API/Weather/Controllers/ForecastController.cs
  WAW.API/Weather/Domain/Models/Forecast.cs
  WAW.API/Weather/Domain/Repositories/IForecastRepository.cs
  WAW.API/Weather/Domain/Services/Communication/ForecastResponse.cs
  WAW.API/Weather/Domain/Services/IForecastService.cs
  WAW.API/Weather/Mapping/ModelToResourceProfile.cs
  WAW.API/Weather/Mapping/ResourceToModelProfile.cs
  WAW.API/Weather/Persistence/Repositories/ForecastRepository.cs
  WAW.API/Weather/Resources/ForecastRequest.cs
  WAW.API/Weather/Resources/ForecastResource.cs
  WAW.API/Weather/Services/ForecastService.cs
Labels: refactor

#13 fix: UserService injection
  WAW.API/Auth/Injection/AuthInjections.cs
Labels: bug

#15 fix: Company domain to Employers
  WAW.API/Employers/Controllers/CompaniesController.cs
  WAW.API/Employers/Domain/Models/Company.cs
  WAW.API/Employers/Domain/Repositories/ICompanyRepository.cs
  WAW.API/Employers/Domain/Services/Communication/CompanyResponse.cs
  WAW.API/Employers/Domain/Services/ICompanyService.cs
  WAW.API/Employers/Injection/CompanyInjections.cs
  WAW.API/Employers/Mapping/CompanyModelToResourceProfile.cs
  WAW.API/Employers/Mapping/CompanyResourceToModelProfile.cs
  WAW.API/Employers/Persistence/Repositories/CompanyRepository.cs
  WAW.API/Employers/Resources/CompanyRequest.cs
  WAW.API/Employers/Resources/CompanyResource.cs
  WAW.API/Employers/Services/CompanyService.cs
  WAW.API/Shared/Injection/AppInjections.cs
  WAW.API/Shared/Mapping/ModelToResourceProfile.cs
  WAW.API/Shared/Mapping/ResourceToModelProfile.cs
  WAW.API/Shared/Persistence/Contexts/AppDbContext.cs
  WAW.API/WAW.API.csproj
Labels: bug

#22 chore(ci): deployment
  .gcloudignore
  .github/workflows/deploy.yml
  .github/workflows/dotnet.yml
  .vscode/settings.json
  .vscode/tasks.json
  WAW.API.Tests/Helpers/AppFactory.cs
  WAW.API.Tests/WAW.API.Tests.csproj
  WAW.API.Tests/packages.lock.json
  WAW.API/Dockerfile
  WAW.API/Health/Controllers/HealthChecksController.cs
  WAW.API/Program.cs
  WAW.API/WAW.API.csproj
  WAW.API/app.yaml
  WAW.API/appsettings.Development.json
  WAW.API/appsettings.json
  WAW.API/packages.lock.json
Labels: ci, chore

#20 feat: Chat
  WAW.API/Auth/Domain/Models/User.cs
  WAW.API/Chat/Controllers/ChatRoomController.cs
  WAW.API/Chat/Controllers/MessageController.cs
  WAW.API/Chat/Domain/Models/ChatRoom.cs
  WAW.API/Chat/Domain/Models/Message.cs
  WAW.API/Chat/Domain/Repositories/IChatRoomRepository.cs
  WAW.API/Chat/Domain/Repositories/IMessageRepository.cs
  WAW.API/Chat/Domain/Services/Communication/ChatRoomResponse.cs
  WAW.API/Chat/Domain/Services/Communication/MessageResponse.cs
  WAW.API/Chat/Domain/Services/IChatRoomService.cs
  WAW.API/Chat/Domain/Services/IMessageService.cs
  WAW.API/Chat/Injection/ChatInjections.cs
  WAW.API/Chat/Mapping/ChatModelToResourceProfile.cs
  WAW.API/Chat/Mapping/ChatResourceToModelProfile.cs
  WAW.API/Chat/Persistence/Repositories/ChatRoomRepository.cs
  WAW.API/Chat/Persistence/Repositories/MessageRepository.cs
  WAW.API/Chat/Resources/ChatRoomRequest.cs
  WAW.API/Chat/Resources/ChatRoomResource.cs
  WAW.API/Chat/Resources/MessageRequest.cs
  WAW.API/Chat/Resources/MessageResource.cs
  WAW.API/Chat/Services/ChatRoomService.cs
  WAW.API/Chat/Services/MessageService.cs
  WAW.API/Shared/Injection/AppInjections.cs
  WAW.API/Shared/Mapping/ModelToResourceProfile.cs
  WAW.API/Shared/Mapping/ResourceToModelProfile.cs
  WAW.API/Shared/Persistence/Contexts/AppDbContext.cs
Labels: enhancement

#23 feat: CORS
  WAW.API/Program.cs
  WAW.API/appsettings.Development.json
  WAW.API/appsettings.json
Labels: enhancement, chore

#28 fix: Chat models and controllers
  WAW.API/Auth/Domain/Models/User.cs
  WAW.API/Auth/Domain/Services/IUserService.cs
  WAW.API/Auth/Resources/UserRequest.cs
  WAW.API/Auth/Resources/UserResource.cs
  WAW.API/Auth/Services/UserService.cs
  WAW.API/Chat/Controllers/ChatRoomController.cs
  WAW.API/Chat/Domain/Models/Message.cs
  WAW.API/Chat/Domain/Repositories/IChatRoomRepository.cs
  WAW.API/Chat/Domain/Services/IChatRoomService.cs
  WAW.API/Chat/Injection/ChatInjections.cs
  WAW.API/Chat/Persistence/Repositories/ChatRoomRepository.cs
  WAW.API/Chat/Resources/ChatRoomRequest.cs
  WAW.API/Chat/Resources/ChatRoomResource.cs
  WAW.API/Chat/Resources/MessageRequest.cs
  WAW.API/Chat/Resources/MessageResource.cs
  WAW.API/Chat/Services/ChatRoomService.cs
  WAW.API/Migrations/20220627172121_User_SomeChanges.Designer.cs
  WAW.API/Migrations/20220627172121_User_SomeChanges.cs
  WAW.API/Migrations/AppDbContextModelSnapshot.cs
  WAW.API/Shared/Persistence/Contexts/AppDbContext.cs
Labels: bug

#29 fix: Delete response
  WAW.API.Tests/Features/Company.feature
  WAW.API/Auth/Controllers/UsersController.cs
  WAW.API/Chat/Controllers/ChatRoomController.cs
  WAW.API/Chat/Controllers/MessageController.cs
  WAW.API/Employers/Controllers/CompaniesController.cs
  WAW.API/Job/Controllers/OffersController.cs
Labels: bug, documentation

#31 refactor: use company id for UserExperienceReq
  WAW.API/Auth/Resources/UserExperienceRequest.cs
  WAW.API/Auth/Resources/UserProjectResource.cs
  WAW.API/Employers/Controllers/CompaniesController.cs
  WAW.API/Job/Controllers/OffersController.cs
Labels: enhancement
